/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(TDMSingle.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(045ff832d149e9965d18df86ed590934)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/jammingSource/TDMSingle.h>
// pydoc.h is automatically generated in the build directory
#include <TDMSingle_pydoc.h>

void bind_TDMSingle(py::module& m)
{

    using TDMSingle    = ::gr::jammingSource::TDMSingle;


    py::class_<TDMSingle, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<TDMSingle>>(m, "TDMSingle", D(TDMSingle))

        .def(py::init(&TDMSingle::make),
           py::arg("period") = 1,
           py::arg("targetFreq") = "0",
           D(TDMSingle,make)
        )
        



        ;




}








