/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-jammingSource
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_JAMMINGSOURCE_API_H
#define INCLUDED_JAMMINGSOURCE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_jammingSource_EXPORTS
#define JAMMINGSOURCE_API __GR_ATTR_EXPORT
#else
#define JAMMINGSOURCE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_JAMMINGSOURCE_API_H */
